from matplotlib.colors import LinearSegmentedColormap

# Color maps
jet_muted_dic = {'red': ((0/6,25/255,25/255),
                         (1/6,25/255,25/255),
                         (2/6,0/255,0/255),
                         (3/6,0/255,0/255),
                         (4/6,230/255,230/255),
                         (5/6,230/255,230/255),
                         (6/6,153/255,153/255)),
             'green':   ((0/6,25/255,25/255),
                         (1/6,102/255,102/255),
                         (2/6,230/255,230/255),
                         (3/6,179/255,179/255),
                         (4/6,230/255,230/255),
                         (5/6,102/255,102/255),
                         (6/6,25/255,25/255)),
             'blue':    ((0/6,153/255,153/255),
                         (1/6,230/255,230/255),
                         (2/6,230/255,230/255),
                         (3/6,0/255,0/255),
                         (4/6,0/255,0/255),
                         (5/6,25/255,25/255),
                         (6/6,25/255,25/255)),
             'alpha':   ((0/6,255/255,255/255),
                         (1/6,255/255,255/255),
                         (2/6,255/255,255/255),
                         (3/6,255/255,255/255),
                         (4/6,255/255,255/255),
                         (5/6,255/255,255/255),
                         (6/6,255/255,255/255))}
jet_muted = LinearSegmentedColormap('JetMuted',jet_muted_dic)

# Hand-coded meta-categories
V1_super2cat = {0:['chair',
                   'guitar',
                   'person',
                   'tablelamp',
                   'trafficcone'],
                1:['donut',
                   'doorknob',
                   'layercake',
                   'sailboat'],
                2:['car',
                   'elephant',
                   'fish',
                   'handgun',
                   'heavycannon',
                   'motorcycle',
                   'piano',
                   'slrcamera',
                   'stapler',
                   'trex'],
                3:['banana']}

L_super2cat = {0:['banana',
                   'layercake',
                   'trafficcone',
                   'sailboat',
                   'trex'],
                1:['person',
                   'guitar',
                   'tablelamp'],
                2:['doorknob',
                   'handgun',
                   'donut',
                   'chair'],
                3:['slrcamera',
                   'elephant',
                   'piano',
                   'fish'],
                4:['car',
                   'heavycannon',
                   'stapler',
                   'motorcycle']}

bp_super2cat = {0:['tablelamp',
                   'person',
                   'guitar',
                   'trafficcone',
                   'chair',
                   'sailboat',
                   'layercake',
                   'elephant',
                   'piano',
                   'donut',
                   'doorknob',
                   'banana',
                   'handgun',
                   'slrcamera'],
                1:['car',
                   'heavycannon',
                   'motorcycle',
                   'stapler',
                   'fish',
                   'trex']}

pn_super2cat = {0:['car',
                   'elephant',
                   'fish',
                   'handgun',
                   'heavycannon',
                   'motorcycle',
                   'piano',
                   'slrcamera',
                   'stapler',
                   'trex',
                   'doorknob',
                   'layercake'],
                2:['banana',
                   'guitar',
                   'person',
                   'sailboat',
                   'tablelamp',
                   'trafficcone',
                   'chair',
                   'donut']}
